sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sbt
  - $HOME/.ivy2

script:
  - ./bin/activator clean coverage test coverageReport
  - ./bin/activator stage
  - docker build -t iannickb/play-java-seed .

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push iannickb/play-java-seed:latest;
    fi
  - if [ "$TRAVIS_TAG" ]; then
    docker tag iannickb/play-java-seed:latest iannickb/play-java-seed:${TRAVIS_TAG:1}
    fi